### ISSUE TITLE
Split the function into a "Raw" and "Advanced" class

### ISSUE THREAD

**Issue by SteveBenz** [techpaul/PS2KeyAdvanced#2]
Are you entertaining outside pull requests to this code?  I ended up doing some serious hacking on the PS2 library (alas, I started with an out of date version), but still, there are some improvements that I could bring from my code up to the libraries here.  (My changes could either go here, in the Advanced library, with a lot of work on my part, or they could go into the Raw library, with less work on my part but it'd probably completely replace that code.)  I'd like to share my work, but I think it'd be dumb to create a competing PS2 library.

**Comment by techpaul** [comment]
You are welcome to make your own version and it depends what changes to advanced or RAW would be thought of
