### ISSUE TITLE
increase buffer ??

### ISSUE THREAD

**Issue by shift838** [techpaul/PS2KeyAdvanced#20]
is there a way to increase the buffered characters amount?  When I use this on one of my Retro computers and if I type something before the program is completely up or before any process is finished; say, "12345" when the program comes up or the process is finished I will only get the first 2-3 characters first typed.

**Comment by techpaul** [comment]
This may well be another delay in your application not processing keys quick enough.

However you can try changing in PS2KeyCode.h the definition for
~~~
#define _RX_BUFFER_SIZE  8
~~~
to
~~~
#define _RX_BUFFER_SIZE  16
~~~

**Comment by shift838** [comment]
I did see that line in the library and changed it to 16 and even 32, but had no effect.

**Comment by techpaul** [comment]
This suggests not reading keyboard quick enough which even for manual keypresses is a very long time in instruction cycles that suggests other things holding up your application.
