### ISSUE TITLE
Digispark Attiny85

### ISSUE THREAD

**Issue by aknik** [techpaul/PS2KeyAdvanced#4]
Any help for using your lib in Digispark ?

Arduino IDE give this error ....
Thanks a lot.

/home/usuario/Arduino/libraries/PS2KeyAdvanced/src/PS2KeyAdvanced.cpp: In member function 'void PS2KeyAdvanced::begin(uint8_t, uint8_t)':
/home/usuario/Arduino/libraries/PS2KeyAdvanced/src/PS2KeyAdvanced.cpp:997:49: error: 'digitalPinToInterrupt' was not declared in this scope
 attachInterrupt( digitalPinToInterrupt( irq_pin ), ps2interrupt, FALLING );
                                                 ^
exit status 1
Error compilando para la tarjeta Digispark (Default - 16.5mhz).

**Comment by techpaul** [comment]
I suspect you do not have interrupot support on that unit or on the pins you have specified
