### ISSUE TITLE
return  PS2_KEY_PAUSE + _FUNCTION == return PS2_KEY_L_SHIFT

### ISSUE THREAD

**Issue by dmkt** [techpaul/PS2KeyAdvanced#5]
https://github.com/techpaul/PS2KeyAdvanced/blob/527f8c8ae9e662fc9be32eb46252fae498a57383/src/PS2KeyAdvanced.cpp#L651

is that correct way of treating "special case of PAUSE key" ?

**Comment by techpaul** [comment]
Yes as that is only sequence that works that way
