### ISSUE TITLE
PS2KeyCode.h

### ISSUE THREAD

**Issue by d-two** [techpaul/PS2KeyAdvanced#9]
Please check your PS2KeyCode.h, i think your keycode is wrong...

#define PS2_KC_STOP     0X38 -> 0X3B

**Comment by techpaul** [comment]
Spent some time checking through documents.

Yes that is a classic typo 8 and B and some fonts  not so viewable.

Update going up soon.

For those who want to know what the key is, it is the multi-media STOP button as opposed to PLAY

**Comment by techpaul** [comment]
Thank you for pointing out the typo a new version is now released as V1.05
